import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
const inter = Inter({ subsets: ['latin'] });
import Header from '../component/header';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck } from '@fortawesome/free-solid-svg-icons';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>El Gitanos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='home_gitan'>
        <h2 className='h1_home'>Orga El Gitanos</h2>
        <div className='container_home'>
          <div className='card_home'>
            <div className='titre_card_home'>
              <h3 className='h3_home'>Recrutement</h3>
            </div>
            <div className='container_text_card_home'>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>avoir 18 ans</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>avoir un bon rp et connaitre le reglement</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>connaitre le language gitan</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>avoir un bon background</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>être actif</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>respect de la hierarchie</p>
              </div>
              <div className='p_check'>
                <FontAwesomeIcon className='icon_check' icon={faCheck} />
                <p>loyauté</p>
              </div>
              <div className='container_button'>
                <Link className='button_discord' href="https://discord.gg/NYgDV8t6gM">Discord</Link>
              </div>
            </div>


          </div>
          <div className='card_home'>
            <div className='titre_card_home'>
              <h3 className='h3_home'>News</h3>
            </div>
            <div className='container_text_card_home'>
              <div className='p_check2'>
                <p> - Dépot du dossier de candidature</p>
                <p> - Création du site internet</p>
                <p> - Création du discord</p>
              </div>
            </div>


          </div>


        </div>
        <div className='container_home2'>
          <div className='card_home'>
            <div className='titre_card_home'>
              <h3 className='h3_home'>Lexique gitan</h3>
            </div>
            <div className='container_text_card_home'>
              <div className='p_check2'>
                <p> - Poucave : une balance</p>
                <p> - Dicave : regarde</p>
                <p> - Bouillave : baiser</p>
                <p> - raclo / racli : garçon / fille</p>
                <p> - Balnave : mentir</p>
                <p> - Bicrave : vendre</p>
                <p> - Chourave : voler</p>
                <p> - Nachave : s'en aller</p>
                <p> - Marave : se niquer, niquer des gens</p>
              </div>
            </div>


          </div>
        </div>
      </main>
    </>
  )
}
