import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Header from '../component/header'
import Footer from '../component/footer';
export default function Membres() {
    return (
        <>
            <Head>
                <title>El Gitanos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className='home_gitan'>
        <div className='container_histoire'>
          <h2 className='h2_histoire'>Nos Membres</h2>
        </div>
        
      </main>
      <Footer/>
        </>
    )
}